"""Add enums

Revision ID: 2b1dae2f783d
Revises: 628206070a07
Create Date: 2024-04-24 01:34:52.113393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b1dae2f783d'
down_revision: Union[str, None] = '628206070a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('type', sa.Enum('TASK', 'BUG', name='task_type'), nullable=True))
    op.add_column('tasks', sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='task_priority'), nullable=True))
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('to_do', 'in_progress', 'code_review', 'dev_test', 'testing', 'done', 'wont_fix', name='task_status'),
               type_=sa.Enum('TO_DO', 'IN_PROGRESS', 'CODE_REVIEW', 'DEV_TEST', 'TESTING', 'DONE', 'WONTFIX', name='task_status'),
               existing_nullable=True)
    op.drop_index('ix_tasks_status', table_name='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('TO_DO', 'IN_PROGRESS', 'CODE_REVIEW', 'DEV_TEST', 'TESTING', 'DONE', 'WONTFIX', name='taskstatus'),
               type_=postgresql.ENUM('to_do', 'in_progress', 'code_review', 'dev_test', 'testing', 'done', 'wont_fix', name='task_status'),
               existing_nullable=True)
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'type')
    # ### end Alembic commands ###
