"""Initial migration2

Revision ID: 2fbe332823f0
Revises: 075f1c92bf3e
Create Date: 2024-04-24 01:18:41.962782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fbe332823f0'
down_revision: Union[str, None] = '075f1c92bf3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('description', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('last_updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tasks_number'), 'tasks', ['number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_number'), table_name='tasks')
    op.drop_column('tasks', 'last_updated_at')
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'description')
    op.drop_column('tasks', 'number')
    # ### end Alembic commands ###
