"""Initialmigration4

RevisionID:628206070a07
Revises:869d352ad3f4
CreateDate:2024-04-2401:25:22.382967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628206070a07'
down_revision: Union[str, None] = '869d352ad3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.Enum('TO_DO', 'IN_PROGRESS', 'CODE_REVIEW', 'DEV_TEST', 'TESTING', 'DONE', 'WONT_FIX', name='task_status'), nullable=True))
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
