"""Fix task model

Revision ID: 7878f5fd1ee5
Revises: 699d36aa78db
Create Date: 2024-04-25 05:25:24.358538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7878f5fd1ee5'
down_revision: Union[str, None] = '699d36aa78db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'type',
               existing_type=postgresql.ENUM('task', 'bug', name='task_type'),
               nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('critical', 'high', 'medium', 'low', name='task_priority'),
               nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('to_do', 'in_progress', 'code_review', 'dev_test', 'testing', 'done', 'wontfix', name='task_status'),
               nullable=False)
    op.alter_column('tasks', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tasks', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('to_do', 'in_progress', 'code_review', 'dev_test', 'testing', 'done', 'wont_fix', name='task_status'),
               nullable=True)
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('critical', 'high', 'medium', 'low', name='task_priority'),
               nullable=True)
    op.alter_column('tasks', 'type',
               existing_type=postgresql.ENUM('task', 'bug', name='task_type'),
               nullable=True)
    # ### end Alembic commands ###
