"""Add FK with tasks for history

Revision ID: ac04868596ee
Revises: 6484608da0ad
Create Date: 2024-04-27 20:51:42.014663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac04868596ee'
down_revision: Union[str, None] = '6484608da0ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_history', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task_history', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_history', type_='foreignkey')
    op.drop_column('task_history', 'task_id')
    # ### end Alembic commands ###
