"""Add task enclosure

Revision ID: ba72321d25f1
Revises: 9ce385334a00
Create Date: 2024-04-26 23:06:37.337358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba72321d25f1'
down_revision: Union[str, None] = '9ce385334a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('to_do', 'in_progress', 'code_review', 'dev_test', 'testing', 'done', 'wontfix', name='task_status'),
               nullable=False)
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('to_do', 'in_progress', 'code_review', 'dev_test', 'testing', 'done', 'wontfix', name='task_status'),
               nullable=True)
    op.drop_column('tasks', 'parent_id')
    # ### end Alembic commands ###
